[package]
name = "rabbe2"
version = "0.1.0"
authors = ["a3r <arrrght@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
lapin-futures = "0.18.0"
tokio = "0.1"
failure = "0.1"
futures = "0.1"
log = "0.4"
serde_json = "1.0"
clap = "2.32.0"
handlebars = "1.1.0"
